---
- name: Run commands on remote cEOS-lab device
  hosts: ceos
  connection: network_cli
  gather_facts: false
  vars:
    ansible_python_interpreter: python
    ansible_network_os: eos
  tasks:
    - name: Execute Arista EOS command
      arista.eos.eos_command:
        commands: show version
      register: version

    - name: Display result
      ansible.builtin.debug:
        msg: "{{ version.stdout }}"

- name: Run commands on remote cEOS-lab device
  hosts: ceos
  connection: netconf
  gather_facts: false
  vars:
    ansible_python_interpreter: python
    ansible_network_os: eos
  tasks:
    - name: Get list of availables YANG schema
      ansible.netcommon.netconf_get:
        display: pretty
        filter: |
          <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
              <schemas>
                  <schema/>
              </schemas>
          </netconf-state>
        lock: never
      register: list_of_schemas

    - name: Display the list of availables YANG schema
      ansible.builtin.debug:
        msg: "{{ list_of_schemas.output }}"
