---
- name: Define and enforce a configuration reference
  hosts: all
  gather_facts: false
  become: true
  become_method: ansible.netcommon.enable
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_python_interpreter: "python"
    ansible_network_os: 'arista.eos.eos'
    ansible_user: admin
    ansible_password: admin
    method: "replaced"
  tasks:
    - name: Get hostvars from the inventory
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
    - name: Set the hostname
      arista.eos.eos_hostname:
        config:
          hostname: "{{ name }}"
        state: "{{ method }}"
    - name: Create interfaces
      arista.eos.eos_l2_interfaces:
        state: "{{ method }}"
        config:
          - name: "{{ item.name }}"
      loop: "{{ hostvars[inventory_hostname].interfaces }}"
    - name: Set Interface config
      arista.eos.eos_l3_interfaces:
        state: "{{ method }}"
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip_addresses.0.address }}"
      loop: "{{ hostvars[inventory_hostname].interfaces }}"
      when: item.ip_addresses | length > 0
    - name: Set BGP config
      arista.eos.eos_bgp_global:
        state: "{{ method }}"
        config:
          as_number: "{{ item.1.autonomous_system.as_number }}"
          # Make a list of all the neighbors using map to generate the appropriate keys
          neighbor: "{{ item.1.peer | map('extract', 'source_ip.address') | map('format', 'peer: {}') | list }}"
      with_nested:
        - "{{ hostvars[inventory_hostname].bgp_routing_instances }}"
        - "{{ item.0.endpoints }}"
      when: item.1.peer | length > 0
