---
- name: Enable RESTCONF
  hosts: all
  gather_facts: false
  become: true
  become_method: ansible.netcommon.enable
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_python_interpreter: python
    ansible_network_os: arista.eos.eos
    ansible_user: admin
    ansible_password: admin
    method: replaced
  tasks:
    - name: Generate HTTPS certificates
      arista.eos.eos_command:
        commands: security pki certificate generate self-signed restconf.crt key restconf.key generate rsa 2048 parameters common-name restconf
    - name: Create SSL Profile
      arista.eos.eos_command:
        commands:
          - conf t
          - management security
          - ssl profile restconf
          - certificate restconf.crt key restconf.key
    - name: Enable RESTCONF
      arista.eos.eos_command:
        commands:
          - conf t
          - management api restconf
          - transport https test
          - ssl profile restconf
